all:
	python manage.py makemigartions
	python manage.py migrate
	python manage.py runserver
migrate:
	python manage.py migrate
mk:
	python manage.py makemigrations
server:
	python manage.py runserver

